# Generated by Django 5.2.7 on 2025-10-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_views_counter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="publication_sign",
            field=models.BooleanField(
                default=False, verbose_name="Отметка о публикации"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите количество просмотров",
                verbose_name="Счетчик просмотров",
            ),
        ),
    ]
