# Generated by Django 5.2.7 on 2025-11-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publication_sign",
            field=models.BooleanField(
                default=False, verbose_name="Отметка о публикации"
            ),
        ),
    ]
